### ISSUE TITLE
skip list insert duplicate value

### ISSUE THREAD

**Issue by Hu1-Li** [LeandroLovisolo/MyDataStructures#1]
I am just working with the skip list, then find the skip list demo.I find that when inserting the same value into skip list, the skip list holds all the duplicate value, just like this:
![screen shot 2015-03-19 at 11 50 28](https://cloud.githubusercontent.com/assets/1465913/6724202/27e9e670-ce2e-11e4-88f6-7d3c8a10f1a7.png)

**Comment by LeandroLovisolo** [comment]
Hi! Thanks for your comment. This is actually by design. In this particular implementation of a skip list, duplicates are allowed.
